language: r
sudo: required
cache: packages
env:
  global:
  - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"
  - HDF5_VERSION=1.8.13
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
before_install:
- chmod +x travis_setup.sh
- "./travis_setup.sh"
r:
- bioc-devel
- bioc-release
notifications:
  slack:
  rooms:
        secure: sFOlT9BYAUZLqt+RDtLdbGbG411FU56IEALGIoPiHHhmCoWEbyaVJfhasRh5SZShhAjUvxiTMPkA05prjrQBHkzVozkPhNPUZSwezp5zaKpsQerBVHtc5jN5xaZinvqLK0TNKk1zq5pnBMwcRg54RVQe/petTsiuttxkmyJSAgztiterifMnhUefaJURNvd2AYvi57agUhu41j3xQnarnXdJR8YZtAaXDoYdC9kckJwrf6ZsBBWCe/P0kg1YZt/86SiCGidcjmNOqbAud7/tKJKzjFaU2R1v8ecyZiGSXWFVfbUt/27Ur+8IzJiV0Qn08Ru6TwJSqS/fbc+2vWYo6MWKkfZtK4HhoWsYXyk7jnOP2DTynFMidthGR+qxLxpBuvQbGtPRgcm1DVjDl2Z3MqXz1RbAmnbCDOWNF21go1yIAKCxgHd2a/2TtLsbJsZwyGwSmrxhoF+CH4kJ2mgKarwyKGTLs5L6/eQfXR31hQc0h0eKMLlBkweTkxOguCrO30cuQvZ+bm/pFmR9doyZLP23/cYbnu0AsxgOa/SJ57MjDG2gKYmuzlBXPhNl30M9OIc0P1WRNHmk6aW4wZn6VKYBOAq1gGMM2k8g5x/OPM01R2c5ZJ7Fwizh4kaocXydfxGoJOSO1JPE+r/G339GgTuXyEekgA0dcF0j3recLyQ=#cicero
        secure: GE+uS71QTe/cbprIirqkggpQVWtHO4mAbiePsLaHw8nl+sg0h67eJVrVGno6msdit7yehYGIqXDYPRm0yuOj4+4NWtBtS3zKcFZE6zjy0FMTMUI5BbNHZERLoGmMmJo9zGIuTbt/+eC6yx+8AB1tRmGoOMgZC+bIiotaZGLt3bXdUEOLvOK0/54FgwwVurMzgECaTpPN+wpedS5YoMLGZroMVyQyhR6uLVKBOGEcfh78GxMP1xctP+k5/brCePjFyl6/QZK2icnPAOtWGuBRzXfv7u0sR7LLVCrbbegWNK1WraFY2qcUufYI4m7d9Agm+cH32me4asfqLIGb7TmEujdVTwH0LjqxF9oEsngrlltJ0myAmSBEJCVm18AXNBHj6dlrgsQsiqDHZYrGIWLbBjwJm7kjAqRlQQZz9PuFgiceUagcNJ71Dc77ekc7jGlag5+O84NAc+bjqGTNVLZv6Dn6aAvxE0oTVX1D5b7RpcIhG1NoO7uxQGTpgZLKT8plDG7xykTH944Mqo8+hPS6JyT/hBxzgCR4OEYJ7shrHoPxVLoPTkU+SzA3F5OeaEb55rm8zW6FRS3YBBOBCL9yzZy8nw+lyZmHVraT7IGQx7/Y8eM9L1sWX+leA5LPXXN8Ff0fPSdlMtVo4EA2lvxf6z5eaFITVM6LHKG0L+ISn6Q=#monocle
